### Health
GET {{adminApiBaseUrl}}/api/v1/health

### Create User
POST {{adminApiBaseUrl}}/api/v1/admin/users
Content-Type: application/json

{
  "email": "patrick@example.com",
  "password": "Sup3rS3cret!",
  "displayName": "Patrick",
  "roles": ["admin"]
}
