[CmdletBinding()]
param(
  [string]$OutputPath = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')) '.env.lxp-gateway.vps'),
  [string]$AdminDomain = 'admin.example.com',
  [string]$GatewayDomain = 'gateway.example.com',
  [string]$DefaultUserEmail = 'ops@example.com',
  [string]$PostgresDb = 'lxp_gateway',
  [string]$PostgresUser = 'lxp_gateway'
)

$ErrorActionPreference = 'Stop'

if (Test-Path -LiteralPath $OutputPath) {
  throw "Refusing to overwrite existing file: $OutputPath"
}

function New-RandomHex {
  param([int]$ByteCount)

  $bytes = New-Object byte[] $ByteCount
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  return ($bytes | ForEach-Object { $_.ToString('x2') }) -join ''
}

function New-RandomBase64 {
  param([int]$ByteCount)

  $bytes = New-Object byte[] $ByteCount
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  return [Convert]::ToBase64String($bytes)
}

$postgresPassword = New-RandomHex -ByteCount 24
$encryptionMasterKey = New-RandomBase64 -ByteCount 32
$emailLookupKey = New-RandomBase64 -ByteCount 32
$cookieSecret = New-RandomHex -ByteCount 32
$jwtPrivateKey = New-RandomHex -ByteCount 32
$openAiCompatApiKey = New-RandomHex -ByteCount 24

$content = @"
# Generated by scripts/Generate-VpsEnv.ps1
# Review this file before first deployment and keep it private.

COMPOSE_PROJECT_NAME=lxp-llm-gateway-vps

LXP_VPS_POSTGRES_DB=$PostgresDb
LXP_VPS_POSTGRES_USER=$PostgresUser
LXP_VPS_POSTGRES_PASSWORD=$postgresPassword
LXP_VPS_DATABASE_SSL=false

LXP_VPS_ENCRYPTION_MASTER_KEY=$encryptionMasterKey
LXP_VPS_EMAIL_LOOKUP_KEY=$emailLookupKey
LXP_VPS_ENCRYPTION_KEY_VERSION=1
LXP_VPS_COOKIE_SECRET=$cookieSecret
LXP_VPS_JWT_PRIVATE_KEY=$jwtPrivateKey

LXP_VPS_REQUEST_BODY_LIMIT=10mb
LXP_VPS_NANOGPT_BASE_URL=https://nano-gpt.com/api/v1

LXP_VPS_ADMIN_WEB_ORIGIN=https://$AdminDomain
LXP_VPS_ADMIN_API_PUBLIC_URL=https://$AdminDomain
LXP_VPS_GATEWAY_API_PUBLIC_URL=https://$GatewayDomain

LXP_VPS_OPENAI_COMPAT_API_KEY=$openAiCompatApiKey
LXP_VPS_OPENAI_COMPAT_DEFAULT_USER_EMAIL=$DefaultUserEmail
LXP_VPS_OPENAI_COMPAT_TRUSTED_IDENTITY_ENABLED=false
LXP_VPS_OPENAI_COMPAT_TRUSTED_EMAIL_HEADER=X-OpenWebUI-User-Email
LXP_VPS_OPENAI_COMPAT_TRUSTED_EMAIL_HEADERS=
LXP_VPS_OPENAI_COMPAT_DEBUG=false
"@

$parent = Split-Path -Parent $OutputPath
if ($parent -and -not (Test-Path -LiteralPath $parent)) {
  New-Item -ItemType Directory -Path $parent | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $content -Encoding utf8NoBOM

Write-Host "Generated VPS env file: $OutputPath"
Write-Host "Admin domain: https://$AdminDomain"
Write-Host "Gateway domain: https://$GatewayDomain"
Write-Host "Default OpenAI-compatible user: $DefaultUserEmail"
