#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_PATH="${1:-$ROOT_DIR/.env.lxp-gateway.vps}"
ADMIN_DOMAIN="${LXP_VPS_ADMIN_DOMAIN:-admin.example.com}"
GATEWAY_DOMAIN="${LXP_VPS_GATEWAY_DOMAIN:-gateway.example.com}"
DEFAULT_USER_EMAIL="${LXP_VPS_DEFAULT_USER_EMAIL:-admin@example.com}"
POSTGRES_DB="${LXP_VPS_POSTGRES_DB:-lxp_gateway}"
POSTGRES_USER="${LXP_VPS_POSTGRES_USER:-lxp_gateway}"

if [[ -f "$OUTPUT_PATH" ]]; then
  echo "Refusing to overwrite existing file: $OUTPUT_PATH"
  echo "Delete it first or pass a different output path."
  exit 1
fi

random_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  head -c "$bytes" /dev/urandom | od -An -vtx1 | tr -d ' \n'
}

random_base64() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes" | tr -d '\n'
    return
  fi

  head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
}

derive_cookie_domain() {
  local admin_domain="$1"
  local gateway_domain="$2"

  IFS='.' read -r -a admin_labels <<<"$admin_domain"
  IFS='.' read -r -a gateway_labels <<<"$gateway_domain"

  local admin_index=$((${#admin_labels[@]} - 1))
  local gateway_index=$((${#gateway_labels[@]} - 1))
  local shared_labels=()

  while [[ $admin_index -ge 0 && $gateway_index -ge 0 ]]; do
    if [[ "${admin_labels[$admin_index]}" != "${gateway_labels[$gateway_index]}" ]]; then
      break
    fi
    shared_labels=("${admin_labels[$admin_index]}" "${shared_labels[@]}")
    admin_index=$((admin_index - 1))
    gateway_index=$((gateway_index - 1))
  done

  if [[ ${#shared_labels[@]} -lt 2 ]]; then
    echo ""
    return
  fi

  local shared_domain
  shared_domain="$(IFS='.'; echo "${shared_labels[*]}")"
  echo ".$shared_domain"
}

POSTGRES_PASSWORD="$(random_hex 24)"
ENCRYPTION_MASTER_KEY="$(random_base64 32)"
EMAIL_LOOKUP_KEY="$(random_base64 32)"
COOKIE_SECRET="$(random_hex 32)"
JWT_PRIVATE_KEY="$(random_hex 32)"
OPENAI_COMPAT_API_KEY="$(random_hex 24)"
COOKIE_DOMAIN="$(derive_cookie_domain "$ADMIN_DOMAIN" "$GATEWAY_DOMAIN")"

cat >"$OUTPUT_PATH" <<EOF
# Generated by scripts/generate-vps-env.sh
# Review this file before first deployment and keep it private.

COMPOSE_PROJECT_NAME=lxp-llm-gateway-vps

LXP_VPS_POSTGRES_DB=$POSTGRES_DB
LXP_VPS_POSTGRES_USER=$POSTGRES_USER
LXP_VPS_POSTGRES_PASSWORD=$POSTGRES_PASSWORD
LXP_VPS_DATABASE_SSL=false

LXP_VPS_ENCRYPTION_MASTER_KEY=$ENCRYPTION_MASTER_KEY
LXP_VPS_EMAIL_LOOKUP_KEY=$EMAIL_LOOKUP_KEY
LXP_VPS_ENCRYPTION_KEY_VERSION=1
LXP_VPS_COOKIE_SECRET=$COOKIE_SECRET
LXP_VPS_COOKIE_DOMAIN=$COOKIE_DOMAIN
LXP_VPS_COOKIE_SECURE=true
LXP_VPS_JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY

LXP_VPS_REQUEST_BODY_LIMIT=10mb
LXP_VPS_NANOGPT_BASE_URL=https://nano-gpt.com/api/v1

LXP_VPS_ADMIN_WEB_ORIGIN=https://$ADMIN_DOMAIN
LXP_VPS_ADMIN_API_PUBLIC_URL=https://$ADMIN_DOMAIN
LXP_VPS_GATEWAY_API_PUBLIC_URL=https://$GATEWAY_DOMAIN

LXP_VPS_OPENAI_COMPAT_API_KEY=$OPENAI_COMPAT_API_KEY
LXP_VPS_OPENAI_COMPAT_DEFAULT_USER_EMAIL=$DEFAULT_USER_EMAIL
LXP_VPS_OPENAI_COMPAT_TRUSTED_IDENTITY_ENABLED=false
LXP_VPS_OPENAI_COMPAT_TRUSTED_EMAIL_HEADER=X-OpenWebUI-User-Email
LXP_VPS_OPENAI_COMPAT_TRUSTED_EMAIL_HEADERS=
LXP_VPS_OPENAI_COMPAT_DEBUG=false
EOF

echo "Generated VPS env file: $OUTPUT_PATH"
echo "Admin domain: https://$ADMIN_DOMAIN"
echo "Gateway domain: https://$GATEWAY_DOMAIN"
echo "Default OpenAI-compatible user: $DEFAULT_USER_EMAIL"
